# Default timezone
default_timezone: Europe/Zurich

# Default language (locale) `en` or `de`
default_locale: en

# Base command without the prefix (!).
# If a list is provided, the first is the main name and the rest are aliases.
base_command:
  - lunch

# Hunger command (same as the `!<base_command> menu` subcommand)
hunger_command:
  - hunger
  - hungry
  - food
  - essen
  - lunchmenu

# Rate limit for individual users, as the number of reminders allowed to fire in an interval
rate_limit: 10
rate_limit_minutes: 60

# Power level needed to create reminders and delete someone else's reminders
admin_power_level: 50

# time_format: strftime format when listing reminders
time_format: "%Y-%m-%d %H:%M %Z"

# URLs of cookpit api https://idapps.ethz.ch/cookpit-pub-services/swagger-ui/
url_facilities: https://idapps.ethz.ch/cookpit-pub-services/v1/facilities?client-id=ethz-wcms&rs-first=0&rs-size=50
url_menus: https://idapps.ethz.ch/cookpit-pub-services/v1/weeklyrotas?client-id=ethz-wcms&rs-first=0&rs-size=50

# Default facilities filter
default_facilities:
  - food market
  - fusion meal

# Default price to show (one of `int`, `ext`, `stud` or `off`)
default_price: int
